// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function reftPad(str, _, _$1) {
  console.log("You most likely installed the wrong package.", "This isn't left-pad, but It's written in ReasonML so that's cool too, right?");
  return str;
}

export {
  reftPad ,
  
}
/* No side effect */
